services:
  - type: web
    name: vending-machine-app
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=1024
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: "PASTE_YOUR_MONGODB_URI_HERE"
      - key: JWT_SECRET
        value: "PASTE_YOUR_JWT_SECRET_HERE"
      - key: FIREBASE_DATABASE_URL
        value: "PASTE_YOUR_FIREBASE_DATABASE_URL_HERE"
      - key: FIREBASE_SERVICE_ACCOUNT
        value: "PASTE_YOUR_SERVICE_ACCOUNT_JSON_HERE"
      - key: RAZORPAY_KEY_ID
        value: "PASTE_YOUR_RAZORPAY_KEY_ID_HERE"
      - key: RAZORPAY_KEY_SECRET
        value: "PASTE_YOUR_RAZORPAY_KEY_SECRET_HERE"
      - key: RAZORPAY_UPI_ID
        value: "PASTE_YOUR_RAZORPAY_UPI_ID_HERE"
      - key: RAZORPAY_WEBHOOK_SECRET
        value: "PASTE_YOUR_RAZORPAY_WEBHOOK_SECRET_HERE"
      - key: BACKEND_URL
        value: "https://vending-machine-app.onrender.com"
