services:
  - type: web
    name: vending-machine-app
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=1024
