services:
  - type: web
    name: vending-machine-app
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=1024
